const User = require("../models/User");
const OTP = require("../models/OTP");
const otpGenerator = require("otp-generator");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const mailSender = require("../utils/mailSender");
const { passwordUpdated } = require("../mail/templates/passwordUpdate");
const Profile = require("../models/Profile");
require("dotenv").config();

//send OTP
exports.sendotp = async (req, res) => {
    try {
        //fetching email from email body
        const { email } = req.body;

        //check if user alredy exist
        const checkUserPresent = await User.findOne({ email });

        //if user already exist then, return response
        if (checkUserPresent) {
            return res.status(400).json({
                success: false,
                message: "User already exists",
            });
        }

        //Checking for the email Invaild
        if (checkUserPresent && checkUserPresent.email !== email) {
            return res.status(400).json({
                success: false,
                message: "You Entered the wrong email",
            });
        }

        //************************************************************** */

        //OTP GENERATION:
        // OTP ko generate krne jaa rhe hai idr
        // This is bkr tarik kuki hum bar bar db m entry check kr rhe hai
        var otp = otpGenerator.generate(6, {
            upperCaseAlphabets: false,
            lowerCaseAlphabets: false,
            specialChars: false,
        });
        console.log("OTP Generated by the System", otp);

        //Check unique OTP or not--- checking the OTP from our DB set
        let result = await OTP.findOne({ otp: otp });

        while (result) {
            otp = otpGenerator(6, {
                upperCaseAlphabets: false,
                lowerCaseAlpahabets: false,
                specialChars: false,
            });
            result = await OTP.findOne({ otp: otp });
        }
        //***************************************************************** */

        // Iss OTP ko Databse m entry krva rhe h, future checking k liye
        const otpPayload = {
            email,
            otp,
        };

        //Entry creation for OTP Generated in DB
        const otpBody = await OTP.create(otpPayload);
        console.log("These are the items present in OTP BODY:", otpBody);
        // return response successful
        res.status(200).json({
            success: true,
            message: "OTP Sent sucessfully",
            otp,
        });

        //************************************ */
    } catch (error) {
        console.log("Error in OTP sending: ", error);
        return res.status(500).json({
            success: false,
            message: error.message,
        });
    }
};

//signUp
exports.signup = async (req, res) => {
    // Data fetch from request ki body
    try {
        const {
            firstName,
            lastName,
            email,
            password,
            confirmPassword,
            accountType,
            contactNumber,
            otp,
        } = req.body;

        // Validate krlo
        if (
            !firstName ||
            !lastName ||
            !email ||
            !password ||
            !confirmPassword ||
            !otp
        ) {
            return res.status(403).json({
                success: false,
                message: "All fields are required to be filed",
            });
        }

        // 2 password match krlo
        if (password !== confirmPassword) {
            return res.status(400).json({
                success: false,
                message:
                    "Password and ConfirmPassword dosen't match please try again",
            });
        }

        // Check user already exist or not
        const existingUser = await User.findOne({ email });
        if (existingUser) {
            return res.status(400).json({
                success: false,
                message: "User already Registered, Please try to login ",
            });
        }

        // Find most recent OTP stored for the user in DB
        const response = await OTP.find({ email })
            .sort({ createdAt: -1 })
            .limit(1);
        console.log(response);

        // Validate OTP
        if (response.length === 0) {
            // OTP not found for the email
            return res.status(400).json({
                success: false,
                message: "The OTP is not valid",
            });
        } else if (otp !== response[0].otp) {
            // Invalid OTP
            return res.status(400).json({
                success: false,
                message: "The OTP is not valid",
            });
        }

        // Hash Password
        const hashedPassword = await bcrypt.hash(password, 10);

        // Create the user
        let approved = "";
        approved === "Instructor" ? (approved = false) : (approved = true);

        // Entry of Hashed password in DB
        const profileDetails = await Profile.create({
            gender: null,
            dateOfBirth: null,
            about: null,
            contactNumber: null,
        });

        // Create the entry for Password
        const user = await User.create({
            firstName,
            lastName,
            email,
            contactNumber,
            password: hashedPassword,
            accountType: accountType,
            additionalDetails: profileDetails._id,
            image: `https://api.dicebear.com/5.x/initials/svg?seed=${firstName} ${lastName}`,
        });

        //Return res
        return res.status(200).json({
            success: true,
            user,
            message: "User is registered successfully",
        });
    } catch (error) {
        console.log(error);
        return res.status(500).json({
            success: false,
            message: "User cannot be registered.Please try again",
        });
    }
    // Returen Resp.
};

//login
exports.login = async (req, res) => {
    try {
        //get data from request ki body
        const { email, password } = req.body;
        //validation data
        if (!email || !password) {
            return res.status(403).json({
                success: false,
                message: "All fields are required, please try again",
            });
        }
        // User check , exist or not
        const user = await User.findOne({ email }).populate(
            "additionalDetails"
        );
        if (!user) {
            return res.status(401).json({
                success: false,
                message: "User is not registerd, please signup first",
            });
        }
        //generate JWT, after password matching
        if (await bcrypt.compare(password, user.password)) {
            const token = jwt.sign(
				{ email: user.email, id: user._id, accountType: user.accountType },
				process.env.JWT_SECRET,
				{
					expiresIn: "24h",
				}
			);
            // //payload
            // const payload = {
            //     email: user.email,
            //     id: user._id,
            //     accountType: user.accountType,
            // };

            // const token = jwt.sign(payload, process.env.JWT_SECRET, {
            //     expiresIn: "24h",
            // });

            //sending this token to user db
            user.token = token;
            user.password = undefined;

            //options
            const options = {
                expires: new Date(Date.now() + 3 * 24 * 60 * 60 * 100),
                httpOnly: true,
            };

            //Create cookie and send message
            res.cookie("token", token, options).status(200).json({
                success: true,
                token,
                user,
                message: "Logged in successfully",
            });
        } else {
            return res.status(401).json({
                success: false,
                message: "Password is incorrect",
            });
        }
    } catch (error) {
        console.log(error);
        return res.status(500).json({
            success: false,
            message: "Login Failure, Please try again",
        });
    }
};

//change password
exports.changePassword = async (req, res) => {
    try {
        //Get data from req body
        const userDetails = await User.findById(req.user.id);

        //get oldPassword, newPassword, confirmNewPassword
        const { oldPassword, newPassword, confirmNewPassword } = req.body;
        //Validate old password
        const isPasswordMatch = await bcrypt.compare(
            oldPassword,
            userDetails.password
        );
        if (!isPasswordMatch) {
            //if old password does not match , return error 401 (Unaurthorized) error
            return res.status(401).json({
                success: false,
                message: "The password is incorrect",
            });
        }

        //Match new password and confirm new password
        // if (newPassword !== confirmNewPassword) {
        //     //If new password and confirm new pasword do not match , retun a 400(Bad requsest ) error
        //     return res.status(400).json({
        //         success: false,
        //         message: "The password and password does not match",
        //     });
        // }

        // update Password in DB
        const encryptedPassword = await bcrypt.hash(newPassword, 10);
        const updatedUserDetails = await User.findByIdAndUpdate(
            req.user.id,
            { password: encryptedPassword },
            { new: true }
        );
        console.log("Updated user details are", updatedUserDetails);

        //Sending mail notification
        try {
            const emailResponse = await mailSender(
                updatedUserDetails.email,  //email
                'Password Updated confirmation',  //Title
                passwordUpdated(
                    updatedUserDetails.email,
                    `Password updated successfully for ${updatedUserDetails.firstName} ${updatedUserDetails.lastName}`
                ) //Body
            );
            console.log("Email sent successfully:", emailResponse.response);
        } catch (error) {
            //If there's an error sending the email, log the error and return a 500(Internal error )
            console.error("Error occured while sending email:", error);
            return res.status(500).json({
                success: false,
                message: "Error occured while sending email",
                error: error.message,
            });
        }

        //Return success response
        return res.status(200).json({
            success: true,
            message: "Password updated successfully",
        });
    } catch (error) {
        // If there's an error updating the password, log the error and return a 500 (Internal Server Error) error
        console.error("Error occurred while updating password:", error);
        return res.status(500).json({
            success: false,
            essage: "Error occurred while updating password",
            error: error.message,
        });
    }
};
